apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks01
  region: ap-southeast-2
iam:
  withOIDC: true

managedNodeGroups:
  - name: base-ng
    amiFamily: Bottlerocket
    instanceType: m6a.4xlarge
    spot: true
    volumeSize: 200
    minSize: 0
    maxSize: 20
    desiredCapacity: 0
  - name: spot-ng
    amiFamily: Bottlerocket
    instanceType: m6a.4xlarge
    spot: true
    volumeSize: 200
    minSize: 2
    maxSize: 20
    desiredCapacity: 3