apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testing01
  region: ap-southeast-2
  version: "1.31"
  tags: 
    Owner: Tutorials and Workshops
    Repository: https://github.com/wagov-dtt/tutorials-and-workshops

autoModeConfig:
  enabled: true

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
  - name: aws-ebs-csi-driver
    configurationValues: |-
      defaultStorageClass:
        enabled: true
  - name: snapshot-controller
  - name: aws-mountpoint-s3-csi-driver

