apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testing01
  region: ap-southeast-2
  version: "1.31"
  tags: 
    Owner: Tutorials and Workshops
    Repository: https://github.com/wagov-dtt/tutorials-and-workshops

addonsConfig:
  autoApplyPodIdentityAssociations: true

iam:
  podIdentityAssociations:
    - namespace: "backups"
      serviceAccountName: "s3access"
      createServiceAccount: true

addons:
  - name: eks-pod-identity-agent
  - name: aws-ebs-csi-driver
    configurationValues: |-
      defaultStorageClass:
        enabled: true
  - name: snapshot-controller
  - name: aws-mountpoint-s3-csi-driver

managedNodeGroups:
  - name: ng01
    amiFamily: Bottlerocket
    instanceTypes: [m6a.xlarge, m6i.xlarge, m7i.xlarge]
    spot: true