apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging01
  region: ap-southeast-2
  version: "1.31"
  tags: 
    Owner: Tutorials and Workshops
    Repository: https://github.com/wagov-dtt/tutorials-and-workshops

vpc:
  nat:
    gateway: HighlyAvailable

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
  - name: eks-pod-identity-agent
  - name: aws-ebs-csi-driver
    configurationValues: |-
      defaultStorageClass:
        enabled: true
  - name: snapshot-controller
  - name: aws-mountpoint-s3-csi-driver

managedNodeGroups:
  - name: ng01
    amiFamily: Bottlerocket
    instanceTypes: [m6a.2xlarge, m6i.2xlarge, m7i.2xlarge]
    desiredCapacity: 3