apiVersion: v1
kind: PersistentVolume
metadata:
  name: $VOLUME
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
    - allow-other
    - prefix=$VOLUME/
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: $BUCKET