[tools]
awscli = { version = "latest", symlink_bins = "true" }
helm = "latest"
kind = "latest"
"aqua:linkerd/linkerd2" = "latest"
k9s = "latest"
kubectl = "latest"
terraform = "latest"
uv = "latest"
"github:tsenart/vegeta" = "latest"
mkcert = "latest"
trivy = "latest"
"github:ddev/ddev" = "latest"
restic = "latest"
