[tools]
awscli = { version = "latest", symlink_bins = "true" }
helm = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
terraform = "latest"
go = "latest"
hugo-extended = "0.161.1"
"github:sass/dart-sass" = { version = "1.99.0", filter_bins = "sass" }
uv = "latest"
"github:tsenart/vegeta" = "latest"
mkcert = "latest"
trivy = "latest"
"github:ddev/ddev" = "latest"
