apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstack-db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kanboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo
