apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
---
{{- if .Values.sso.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstack-db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kanboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo
