name: drupal
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
omit_containers: [db]
# Disable ddev mount/settings management
disable_settings_management: true
no_project_mount: true
performance_mode: none
# Using below global config also uses hardened containers and turns of unused services
# ddev config global --use-hardened-images --omit-containers=ddev-ssh-agent,ddev-router
