# Goose configuration for LiteLLM + Bedrock
# Copy to ~/.config/goose/profiles.yaml

default:
  provider: openai
  model: claude
  extensions:
    # Core tools - shell, file editing, code analysis
    - developer
    # Automation - screenshots, web scraping, desktop control
    - computercontroller

# LiteLLM proxy settings (fake key is fine, Bedrock uses AWS auth)
OPENAI_API_KEY: "sk-litellm-proxy"
OPENAI_BASE_URL: "http://localhost:4000"
