services:
  railpack:
    container_name: "ddev-${DDEV_SITENAME}-railpack"
    image: ${DDEV_SITENAME}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
    ports:
      - "8080:80"
    expose:
      - "80"
    environment:
      IS_DDEV_PROJECT: "true"
