apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debian-debug
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: debian-debug
  template:
    metadata:
      labels:
        app: debian-debug
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: debian-debug
        image: debian:bookworm-slim
        command: ["sleep", "infinity"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
          mountPropagation: Bidirectional
      volumes:
      - name: dev
        hostPath:
          path: /dev
          type: Directory