apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: everest-core
spec:
  chart: everest
  repo: https://percona.github.io/percona-helm-charts
  createNamespace: true
  targetNamespace: "everest-system"
  set:
    server.initialAdminPassword: "everest"

