# ClusterSecretStore - cluster-wide backend configuration
# Why ClusterSecretStore vs SecretStore: One config for all namespaces.
# SecretStore is namespace-scoped if you need per-namespace IAM roles.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        # Pod Identity - no credentials stored, uses IAM role
        # Requires Pod Identity association for external-secrets SA
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
