# rclone serve s3 - local S3-compatible storage for DuckLake data
apiVersion: v1
kind: Service
metadata:
  name: rclone-s3
  labels:
    app: rclone-s3
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    name: s3
  selector:
    app: rclone-s3
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rclone-s3
spec:
  selector:
    matchLabels:
      app: rclone-s3
  serviceName: "rclone-s3"
  template:
    metadata:
      labels:
        app: rclone-s3
    spec:
      containers:
      - name: rclone
        image: rclone/rclone:latest
        args:
          - serve
          - s3
          - /data
          - --addr=:8080
          - --auth-key=,
        ports:
        - containerPort: 8080
          name: s3
        volumeMounts:
        - name: s3local
          mountPath: /data
      volumes:
      - name: s3local
        persistentVolumeClaim:
          claimName: s3local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
