apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: training01
  region: ap-southeast-2
  version: "1.32"

autoModeConfig:
  enabled: true

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
- name: snapshot-controller
  version: latest
- name: amazon-cloudwatch-observability
  version: latest
- name: aws-efs-csi-driver
  version: latest

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]