# Docs: https://rclone.org/docs/ and https://rclone.org/s3/
# Below is tweaked for very high-concurrency Amazon S3 copies of many small files on an 8-core host.
# Benchmarked at about 2500 files per second
# S3 scales by prefix, see https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html
[s3]
type = s3
provider = AWS
env_auth = true
global.checksum = true
global.fast-list = true
global.transfers = 600
global.checkers = 2400
global.multi-thread-streams = 0

# Docs: https://rclone.org/union/
[overlay]
type = union
# Syntax: /local/path remote:bucket:ro
upstreams = ./overlay s3:<bucket>/<folder>:ro

# ACTION POLICY: 'epff' (Endpoint First Found) is safer for overlays than 'epall'.
# We only want to delete/rename on the first writable remote found (local),
# not try to force actions on everything.
action_policy = epff
create_policy = epff
search_policy = epall

# Docs: https://rclone.org/commands/rclone_serve_s3/
# Easy way to list/validate and mount local s3 served
# using e.g. 'rclone serve overlay:'
[serves3]
type = s3
provider = Rclone
endpoint = http://127.0.0.1:8080/
use_multipart_uploads = false
