apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
  volumeName: minio-data
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /dev/shm --console-address :9090
        volumeMounts:
        - mountPath: /data
          name: minio-data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data