apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: mongodb01
spec:
  monitoring: {}
  engine:
    replicas: 1
    resources:
      cpu: "1"
      memory: 4G
    storage:
      size: 25Gi
    type: psmdb
  proxy:
    expose:
      type: internal