apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: mysql01
spec:
  monitoring: {}
  engine:
    type: pxc
    config: |
      [mysqld]
      pxc_strict_mode=PERMISSIVE
    replicas: 1
    storage:
      size: 15G
    resources:
      cpu: 600m
      memory: 1G
  proxy:
    replicas: 1
    type: haproxy