# ExternalSecret - references a secret in AWS Secrets Manager
# Creates a K8s Secret named 'db-creds' in secrets-demo namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: secrets-demo
spec:
  # How often to sync (default 1h, we use 5m for demo)
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    # K8s Secret name that will be created
    name: db-creds
    creationPolicy: Owner
  data:
    # Map AWS secret JSON keys to K8s Secret keys
    - secretKey: username
      remoteRef:
        key: training/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: training/db-credentials
        property: password
