apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: duckdb
  labels:
    app: duckdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckdb
  template:
    metadata:
      labels:
        app: duckdb
    spec:
      containers:
      - name: duckdb
        image: traefik/whoami
        ports:
        - containerPort: 80
        env:
          - name: secretversion
            value: 43a0f019-7fc0-4409-a994-f9ea35ba5866
          - {name: FRUIT, valueFrom: {secretKeyRef: {name: secret01, key: favouritefruit}}}
          - {name: MOVIE, valueFrom: {secretKeyRef: {name: secret01, key: favouritemovie}}}
          - {name: AAAH, valueFrom: {secretKeyRef: {name: secret01, key: Multiline-craziness}}}

