# MySQL (Percona 8.0) with sysbench test data
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: s3-test
stringData:
  MYSQL_ROOT_PASSWORD: testpass
  MYSQL_DATABASE: sbtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: s3-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: percona:8.0
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: s3-test
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-prepare
  namespace: s3-test
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-mysql
        image: percona:8.0
        command: ["sh", "-c", "until mysqladmin ping -h mysql -u root -ptestpass; do sleep 2; done"]
      containers:
      - name: sysbench
        image: perconalab/sysbench:1.1
        command: ["sysbench"]
        args: ["--db-driver=mysql", "--mysql-host=mysql", "--mysql-user=root", 
               "--mysql-password=testpass", "--mysql-db=sbtest", 
               "--tables=2", "--table-size=1000", "oltp_read_write", "prepare"]
