# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - ../../base
  - ../../everest
  - minio.yaml

commonAnnotations:
  targetCluster: minikube